### ISSUE TITLE
iphone not works

### ISSUE THREAD

**Issue by vitorizkiimanda** [halilozel1903/PictureinPictureApp#2]
i tried to launch the app. Works in Ipad emulator but doesnt work at all in iphone emulator just blank white screen.
![image](https://user-images.githubusercontent.com/28048320/112257422-5fcaab00-8c97-11eb-8586-dbe827329e63.png)

**Comment by 92pino** [comment]
@vitorizkiimanda 
If you fix the autolayout of the button, it is displayed normally on the screen.

**Comment by vitorizkiimanda** [comment]
hai, thanks for the reply
can you provide more details about it? thanks

>

**Comment by halilozel1903** [comment]
Hi,

PIP is supporting only iPad Devices. You cannot use iPhone devices but You will use with iOS 14.

https://9to5mac.com/2020/09/17/how-to-picture-in-picture-video-iphone-ios-14/ 


![Simulator Screen Shot - iPad Pro (12 9-inch) (5th generation) - 2021-07-05 at 14 41 52](https://user-images.githubusercontent.com/22895813/124466568-6e992180-dd9f-11eb-891a-1fb24ba0d7b8.png)

![Simulator Screen Shot - iPad Pro (12 9-inch) (5th generation) - 2021-07-05 at 14 44 08](https://user-images.githubusercontent.com/22895813/124466647-7e186a80-dd9f-11eb-9243-e7a77ad38b3a.png)
